services:
  spark-master:
    container_name: da-spark-master
    build:
      context: .
      dockerfile: Dockerfile  # specify if different from default
    image: da-spark-image
    entrypoint: ["./entrypoint.sh", "master"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # gives more time for service to stabilize
    volumes:
      - ../data:/opt/spark/data
      - ./spark_apps:/opt/spark/spark_apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-history-server:
    container_name: da-spark-history
    image: da-spark-image
    entrypoint: ["./entrypoint.sh", "history"]
    volumes:
      - spark-logs:/opt/spark/spark-events
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    ports:
      - "18080:18080"

  spark-worker:
    container_name: da-spark-worker
    image: da-spark-image
    entrypoint: ["./entrypoint.sh", "worker"]
    volumes:
      - ../data:/opt/spark/data
      - ./spark_apps:/opt/spark/spark_apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    depends_on:
      - spark-master

volumes:
  spark-logs:
    driver: local
    driver_opts:
      type: none
      device: /tmp/spark-events
      o: bind

